apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sf
  template:
    metadata:
      labels:
        app: nginx-sf
    spec:
      initContainers:
      - name: generate-htpasswd
        image: alpine
        command:
        - /bin/sh
        - -c
        - |
          echo "$AUTH_CREDS" > /etc/nginx/auth/.htpasswd
        env:
        - name: AUTH_CREDS
          valueFrom:
            secretKeyRef:
              name: auth-basic
              key: .htpasswd
        volumeMounts:
        - name: auth-volume
          mountPath: /etc/nginx/auth
          
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: auth-volume
          mountPath: /etc/nginx/auth
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: auth-volume
        emptyDir: {}